/* glide2.h - MGA-Glide clean-room Glide 2.x interface.
 * GENERATED by tools/abi/gen_header.py from abi/ - do not edit.
 * Glide is a trademark of its owner; see the project README. */
#ifndef MGAGLIDE_GLIDE2_H
#define MGAGLIDE_GLIDE2_H

#if defined(__WATCOMC__)
#  define GLIDE_API __stdcall
#elif defined(__GNUC__) && defined(__i386__)
#  define GLIDE_API __attribute__((stdcall))
#else
#  define GLIDE_API
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* ---- Base types ------------------------------------------------------ */
typedef unsigned char  FxU8;
typedef signed char    FxI8;
typedef unsigned short FxU16;
typedef signed short   FxI16;
typedef unsigned int   FxU32;
typedef signed int     FxI32;
typedef FxI32          FxBool;
typedef float          FxFloat;
#define FXTRUE  1
#define FXFALSE 0

/* ---- Scalar Glide types (all passed as 32-bit stack slots) ----------- */
typedef FxU32 GrColor_t;
typedef FxU8  GrAlpha_t;
typedef FxU32 GrMipMapId_t;
typedef FxU8  GrFog_t;
typedef FxI32 GrChipID_t;
typedef FxI32 GrCombineFunction_t;
typedef FxI32 GrCombineFactor_t;
typedef FxI32 GrCombineLocal_t;
typedef FxI32 GrCombineOther_t;
typedef FxI32 GrAlphaSource_t;
typedef FxI32 GrColorCombineFnc_t;
typedef FxI32 GrAlphaBlendFnc_t;
typedef FxI32 GrAspectRatio_t;
typedef FxI32 GrBuffer_t;
typedef FxI32 GrChromakeyMode_t;
typedef FxI32 GrChromaRangeMode_t;
typedef FxI32 GrCmpFnc_t;
typedef FxI32 GrColorFormat_t;
typedef FxI32 GrCullMode_t;
typedef FxI32 GrDepthBufferMode_t;
typedef FxI32 GrDitherMode_t;
typedef FxI32 GrFogMode_t;
typedef FxU32 GrLock_t;
typedef FxI32 GrLfbBypassMode_t;
typedef FxI32 GrLfbWriteMode_t;
typedef FxI32 GrOriginLocation_t;
typedef FxI32 GrLOD_t;
typedef FxI32 GrMipMapMode_t;
typedef FxI32 GrSmoothingMode_t;
typedef FxI32 GrTextureClampMode_t;
typedef FxI32 GrTextureCombineFnc_t;
typedef FxI32 GrTextureFilterMode_t;
typedef FxI32 GrTextureFormat_t;
typedef FxU32 GrTexTable_t;
typedef FxU32 GrNCCTable_t;
typedef FxU32 GrTexBaseRange_t;
typedef FxU32 GrEnableMode_t;
typedef FxU32 GrCoordinateSpaceMode_t;
typedef FxI32 GrLfbSrcFmt_t;
typedef FxU32 GrHint_t;
typedef FxI32 GrSstType;
typedef FxU32 GrScreenResolution_t;
typedef FxU32 GrScreenRefresh_t;
typedef FxU32 GrMPTextureCombineFnc_t;

typedef void (GLIDE_API *GrProc)(void);
/* The error callback is invoked through an adapter in the runtime that
 * satisfies both register- and stack-convention callers. */
typedef void (*GrErrorCallbackFnc_t)(const char *string, FxBool fatal);

/* ---- Structures (layouts fixed by the shipped ABI; see docs/abi-facts.md) */
#define GLIDE_NUM_TMU        2
#define MAX_NUM_SST          4
#define GLIDE_STATE_PAD_SIZE 312

typedef struct {
    float sow;
    float tow;
    float oow;
} GrTmuVertex;

typedef struct {
    float x, y, z;              /* screen x, y; z is ignored */
    float r, g, b;              /* 0..255 */
    float ooz;                  /* 65535/Z */
    float a;                    /* 0..255 */
    float oow;                  /* 1/W */
    GrTmuVertex tmuvtx[GLIDE_NUM_TMU];
} GrVertex;

typedef struct {
    int                size;
    void              *lfbPtr;
    FxU32              strideInBytes;
    GrLfbWriteMode_t   writeMode;
    GrOriginLocation_t origin;
} GrLfbInfo_t;

typedef struct { char pad[GLIDE_STATE_PAD_SIZE]; } GrState;

typedef struct {
    GrLOD_t           smallLod;
    GrLOD_t           largeLod;
    GrAspectRatio_t   aspectRatio;
    GrTextureFormat_t format;
    void             *data;
} GrTexInfo;

typedef struct { int tmuRev; int tmuRam; } GrTMUConfig_t;

typedef struct {
    int           fbRam;
    int           fbiRev;
    int           nTexelfx;
    FxBool        sliDetect;
    GrTMUConfig_t tmuConfig[GLIDE_NUM_TMU];
} GrVoodooConfig_t;

typedef struct {
    int           fbRam;
    int           nTexelfx;
    GrTMUConfig_t tmuConfig;
} GrSst96Config_t;

typedef GrVoodooConfig_t GrVoodoo2Config_t;
typedef struct { int rev; } GrAT3DConfig_t;

typedef struct {
    int num_sst;
    struct {
        GrSstType type;
        union {
            GrVoodooConfig_t  VoodooConfig;
            GrSst96Config_t   SST96Config;
            GrAT3DConfig_t    AT3DConfig;
            GrVoodoo2Config_t Voodoo2Config;
        } sstBoard;
    } SSTs[MAX_NUM_SST];
} GrHwConfiguration;

typedef struct {
    FxU32 pixelsIn;
    FxU32 chromaFail;
    FxU32 zFuncFail;
    FxU32 aFuncFail;
    FxU32 pixelsOut;
} GrSstPerfStats_t;

typedef struct {
    FxU32             width, height;
    int               small_lod, large_lod;
    GrAspectRatio_t   aspect_ratio;
    GrTextureFormat_t format;
} Gu3dfHeader;

typedef struct {
    FxU8  yRGB[16];
    FxI16 iRGB[4][3];
    FxI16 qRGB[4][3];
    FxU32 packed_data[12];
} GuNccTable;

typedef struct { FxU32 data[256]; } GuTexPalette;

typedef union {
    GuNccTable   nccTable;
    GuTexPalette palette;
} GuTexTable;

typedef struct {
    Gu3dfHeader header;
    GuTexTable  table;
    void       *data;
    FxU32       mem_required;
} Gu3dfInfo;

typedef struct {
    int                   sst;
    FxBool                valid;
    int                   width, height;
    GrAspectRatio_t       aspect_ratio;
    void                 *data;
    GrTextureFormat_t     format;
    GrMipMapMode_t        mipmap_mode;
    GrTextureFilterMode_t magfilter_mode;
    GrTextureFilterMode_t minfilter_mode;
    GrTextureClampMode_t  s_clamp_mode;
    GrTextureClampMode_t  t_clamp_mode;
    FxU32                 tLOD;
    FxU32                 tTextureMode;
    FxU32                 lod_bias;
    GrLOD_t               lod_min, lod_max;
    int                   tmu;
    FxU32                 odd_even_mask;
    FxU32                 tmu_base_address;
    FxBool                trilinear;
    GuNccTable            ncc_table;
} GrMipMapInfo;

/* ---- Constants (abi/constants.tsv) --------------------------------- */
#define GR_FOG_TABLE_SIZE                        0x40
#define GR_ZDEPTHVALUE_NEAREST                   0xffff
#define GR_ZDEPTHVALUE_FARTHEST                  0x0
#define GR_WDEPTHVALUE_NEAREST                   0x0
#define GR_WDEPTHVALUE_FARTHEST                  0xffff
#define GR_MIPMAPLEVELMASK_EVEN                  0x1
#define GR_MIPMAPLEVELMASK_ODD                   0x2
#define GR_MIPMAPLEVELMASK_BOTH                  0x3
#define GR_LODBIAS_BILINEAR                      0x0
#define GR_LODBIAS_TRILINEAR                     0x0
#define GR_TMU0                                  0x0
#define GR_TMU1                                  0x1
#define GR_TMU2                                  0x2
#define GR_FBI                                   0x3
#define GR_COMBINE_FUNCTION_ZERO                 0x0
#define GR_COMBINE_FUNCTION_NONE                 0x0
#define GR_COMBINE_FUNCTION_LOCAL                0x1
#define GR_COMBINE_FUNCTION_LOCAL_ALPHA          0x2
#define GR_COMBINE_FUNCTION_SCALE_OTHER          0x3
#define GR_COMBINE_FUNCTION_BLEND_OTHER          0x3
#define GR_COMBINE_FUNCTION_SCALE_OTHER_ADD_LOCAL 0x4
#define GR_COMBINE_FUNCTION_SCALE_OTHER_ADD_LOCAL_ALPHA 0x5
#define GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL 0x6
#define GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL_ADD_LOCAL 0x7
#define GR_COMBINE_FUNCTION_BLEND                0x7
#define GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL_ADD_LOCAL_ALPHA 0x8
#define GR_COMBINE_FUNCTION_SCALE_MINUS_LOCAL_ADD_LOCAL 0x9
#define GR_COMBINE_FUNCTION_BLEND_LOCAL          0x9
#define GR_COMBINE_FUNCTION_SCALE_MINUS_LOCAL_ADD_LOCAL_ALPHA 0x10
#define GR_COMBINE_FACTOR_ZERO                   0x0
#define GR_COMBINE_FACTOR_NONE                   0x0
#define GR_COMBINE_FACTOR_LOCAL                  0x1
#define GR_COMBINE_FACTOR_OTHER_ALPHA            0x2
#define GR_COMBINE_FACTOR_LOCAL_ALPHA            0x3
#define GR_COMBINE_FACTOR_TEXTURE_ALPHA          0x4
#define GR_COMBINE_FACTOR_TEXTURE_RGB            0x5
#define GR_COMBINE_FACTOR_DETAIL_FACTOR          0x4
#define GR_COMBINE_FACTOR_LOD_FRACTION           0x5
#define GR_COMBINE_FACTOR_ONE                    0x8
#define GR_COMBINE_FACTOR_ONE_MINUS_LOCAL        0x9
#define GR_COMBINE_FACTOR_ONE_MINUS_OTHER_ALPHA  0xa
#define GR_COMBINE_FACTOR_ONE_MINUS_LOCAL_ALPHA  0xb
#define GR_COMBINE_FACTOR_ONE_MINUS_TEXTURE_ALPHA 0xc
#define GR_COMBINE_FACTOR_ONE_MINUS_DETAIL_FACTOR 0xc
#define GR_COMBINE_FACTOR_ONE_MINUS_LOD_FRACTION 0xd
#define GR_COMBINE_LOCAL_ITERATED                0x0
#define GR_COMBINE_LOCAL_CONSTANT                0x1
#define GR_COMBINE_LOCAL_NONE                    0x1
#define GR_COMBINE_LOCAL_DEPTH                   0x2
#define GR_COMBINE_OTHER_ITERATED                0x0
#define GR_COMBINE_OTHER_TEXTURE                 0x1
#define GR_COMBINE_OTHER_CONSTANT                0x2
#define GR_COMBINE_OTHER_NONE                    0x2
#define GR_ALPHASOURCE_CC_ALPHA                  0x0
#define GR_ALPHASOURCE_ITERATED_ALPHA            0x1
#define GR_ALPHASOURCE_TEXTURE_ALPHA             0x2
#define GR_ALPHASOURCE_TEXTURE_ALPHA_TIMES_ITERATED_ALPHA 0x3
#define GR_COLORCOMBINE_ZERO                     0x0
#define GR_COLORCOMBINE_CCRGB                    0x1
#define GR_COLORCOMBINE_ITRGB                    0x2
#define GR_COLORCOMBINE_ITRGB_DELTA0             0x3
#define GR_COLORCOMBINE_DECAL_TEXTURE            0x4
#define GR_COLORCOMBINE_TEXTURE_TIMES_CCRGB      0x5
#define GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB      0x6
#define GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB_DELTA0 0x7
#define GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB_ADD_ALPHA 0x8
#define GR_COLORCOMBINE_TEXTURE_TIMES_ALPHA      0x9
#define GR_COLORCOMBINE_TEXTURE_TIMES_ALPHA_ADD_ITRGB 0xa
#define GR_COLORCOMBINE_TEXTURE_ADD_ITRGB        0xb
#define GR_COLORCOMBINE_TEXTURE_SUB_ITRGB        0xc
#define GR_COLORCOMBINE_CCRGB_BLEND_ITRGB_ON_TEXALPHA 0xd
#define GR_COLORCOMBINE_DIFF_SPEC_A              0xe
#define GR_COLORCOMBINE_DIFF_SPEC_B              0xf
#define GR_COLORCOMBINE_ONE                      0x10
#define GR_BLEND_ZERO                            0x0
#define GR_BLEND_SRC_ALPHA                       0x1
#define GR_BLEND_SRC_COLOR                       0x2
#define GR_BLEND_DST_COLOR                       0x2
#define GR_BLEND_DST_ALPHA                       0x3
#define GR_BLEND_ONE                             0x4
#define GR_BLEND_ONE_MINUS_SRC_ALPHA             0x5
#define GR_BLEND_ONE_MINUS_SRC_COLOR             0x6
#define GR_BLEND_ONE_MINUS_DST_COLOR             0x6
#define GR_BLEND_ONE_MINUS_DST_ALPHA             0x7
#define GR_BLEND_RESERVED_8                      0x8
#define GR_BLEND_RESERVED_9                      0x9
#define GR_BLEND_RESERVED_A                      0xa
#define GR_BLEND_RESERVED_B                      0xb
#define GR_BLEND_RESERVED_C                      0xc
#define GR_BLEND_RESERVED_D                      0xd
#define GR_BLEND_RESERVED_E                      0xe
#define GR_BLEND_ALPHA_SATURATE                  0xf
#define GR_BLEND_PREFOG_COLOR                    0xf
#define GR_ASPECT_8x1                            0x0
#define GR_ASPECT_4x1                            0x1
#define GR_ASPECT_2x1                            0x2
#define GR_ASPECT_1x1                            0x3
#define GR_ASPECT_1x2                            0x4
#define GR_ASPECT_1x4                            0x5
#define GR_ASPECT_1x8                            0x6
#define GR_BUFFER_FRONTBUFFER                    0x0
#define GR_BUFFER_BACKBUFFER                     0x1
#define GR_BUFFER_AUXBUFFER                      0x2
#define GR_BUFFER_DEPTHBUFFER                    0x3
#define GR_BUFFER_ALPHABUFFER                    0x4
#define GR_BUFFER_TRIPLEBUFFER                   0x5
#define GR_CHROMAKEY_DISABLE                     0x0
#define GR_CHROMAKEY_ENABLE                      0x1
#define GR_CHROMARANGE_RGB_ANY                   0x0
#define GR_CHROMARANGE_RGb_ANY                   0x1
#define GR_CHROMARANGE_RgB_ANY                   0x2
#define GR_CHROMARANGE_Rgb_ANY                   0x3
#define GR_CHROMARANGE_rGB_ANY                   0x4
#define GR_CHROMARANGE_rGb_ANY                   0x5
#define GR_CHROMARANGE_rgB_ANY                   0x6
#define GR_CHROMARANGE_rgb_ANY                   0x7
#define GR_CHROMARANGE_RGB_ALL                   0x8
#define GR_CHROMARANGE_RGb_ALL                   0x9
#define GR_CHROMARANGE_RgB_ALL                   0xa
#define GR_CHROMARANGE_Rgb_ALL                   0xb
#define GR_CHROMARANGE_rGB_ALL                   0xc
#define GR_CHROMARANGE_rGb_ALL                   0xd
#define GR_CHROMARANGE_rgB_ALL                   0xe
#define GR_CHROMARANGE_rgb_ALL                   0xf
#define GR_CMP_NEVER                             0x0
#define GR_CMP_LESS                              0x1
#define GR_CMP_EQUAL                             0x2
#define GR_CMP_LEQUAL                            0x3
#define GR_CMP_GREATER                           0x4
#define GR_CMP_NOTEQUAL                          0x5
#define GR_CMP_GEQUAL                            0x6
#define GR_CMP_ALWAYS                            0x7
#define GR_COLORFORMAT_ARGB                      0x0
#define GR_COLORFORMAT_ABGR                      0x1
#define GR_COLORFORMAT_RGBA                      0x2
#define GR_COLORFORMAT_BGRA                      0x3
#define GR_CULL_DISABLE                          0x0
#define GR_CULL_NEGATIVE                         0x1
#define GR_CULL_POSITIVE                         0x2
#define GR_DEPTHBUFFER_DISABLE                   0x0
#define GR_DEPTHBUFFER_ZBUFFER                   0x1
#define GR_DEPTHBUFFER_WBUFFER                   0x2
#define GR_DEPTHBUFFER_ZBUFFER_COMPARE_TO_BIAS   0x3
#define GR_DEPTHBUFFER_WBUFFER_COMPARE_TO_BIAS   0x4
#define GR_DITHER_DISABLE                        0x0
#define GR_DITHER_2x2                            0x1
#define GR_DITHER_4x4                            0x2
#define GR_FOG_DISABLE                           0x0
#define GR_FOG_WITH_ITERATED_ALPHA               0x1
#define GR_FOG_WITH_TABLE                        0x2
#define GR_FOG_WITH_ITERATED_Z                   0x3
#define GR_FOG_MULT2                             0x100
#define GR_FOG_ADD2                              0x200
#define GR_LFB_READ_ONLY                         0x0
#define GR_LFB_WRITE_ONLY                        0x1
#define GR_LFB_IDLE                              0x0
#define GR_LFB_NOIDLE                            0x10
#define GR_LFBBYPASS_DISABLE                     0x0
#define GR_LFBBYPASS_ENABLE                      0x1
#define GR_LFBWRITEMODE_565                      0x0
#define GR_LFBWRITEMODE_555                      0x1
#define GR_LFBWRITEMODE_1555                     0x2
#define GR_LFBWRITEMODE_RESERVED1                0x3
#define GR_LFBWRITEMODE_888                      0x4
#define GR_LFBWRITEMODE_8888                     0x5
#define GR_LFBWRITEMODE_RESERVED2                0x6
#define GR_LFBWRITEMODE_RESERVED3                0x7
#define GR_LFBWRITEMODE_RESERVED4                0x8
#define GR_LFBWRITEMODE_RESERVED5                0x9
#define GR_LFBWRITEMODE_RESERVED6                0xa
#define GR_LFBWRITEMODE_RESERVED7                0xb
#define GR_LFBWRITEMODE_565_DEPTH                0xc
#define GR_LFBWRITEMODE_555_DEPTH                0xd
#define GR_LFBWRITEMODE_1555_DEPTH               0xe
#define GR_LFBWRITEMODE_ZA16                     0xf
#define GR_LFBWRITEMODE_ANY                      0xff
#define GR_ORIGIN_UPPER_LEFT                     0x0
#define GR_ORIGIN_LOWER_LEFT                     0x1
#define GR_ORIGIN_ANY                            0xff
#define GR_LOD_256                               0x0
#define GR_LOD_128                               0x1
#define GR_LOD_64                                0x2
#define GR_LOD_32                                0x3
#define GR_LOD_16                                0x4
#define GR_LOD_8                                 0x5
#define GR_LOD_4                                 0x6
#define GR_LOD_2                                 0x7
#define GR_LOD_1                                 0x8
#define GR_MIPMAP_DISABLE                        0x0
#define GR_MIPMAP_NEAREST                        0x1
#define GR_MIPMAP_NEAREST_DITHER                 0x2
#define GR_SMOOTHING_DISABLE                     0x0
#define GR_SMOOTHING_ENABLE                      0x1
#define GR_TEXTURECLAMP_WRAP                     0x0
#define GR_TEXTURECLAMP_CLAMP                    0x1
#define GR_TEXTURECOMBINE_ZERO                   0x0
#define GR_TEXTURECOMBINE_DECAL                  0x1
#define GR_TEXTURECOMBINE_OTHER                  0x2
#define GR_TEXTURECOMBINE_ADD                    0x3
#define GR_TEXTURECOMBINE_MULTIPLY               0x4
#define GR_TEXTURECOMBINE_SUBTRACT               0x5
#define GR_TEXTURECOMBINE_DETAIL                 0x6
#define GR_TEXTURECOMBINE_DETAIL_OTHER           0x7
#define GR_TEXTURECOMBINE_TRILINEAR_ODD          0x8
#define GR_TEXTURECOMBINE_TRILINEAR_EVEN         0x9
#define GR_TEXTURECOMBINE_ONE                    0xa
#define GR_TEXTUREFILTER_POINT_SAMPLED           0x0
#define GR_TEXTUREFILTER_BILINEAR                0x1
#define GR_TEXFMT_8BIT                           0x0
#define GR_TEXFMT_RGB_332                        0x0
#define GR_TEXFMT_YIQ_422                        0x1
#define GR_TEXFMT_ALPHA_8                        0x2
#define GR_TEXFMT_INTENSITY_8                    0x3
#define GR_TEXFMT_ALPHA_INTENSITY_44             0x4
#define GR_TEXFMT_P_8                            0x5
#define GR_TEXFMT_RSVD0                          0x6
#define GR_TEXFMT_RSVD1                          0x7
#define GR_TEXFMT_16BIT                          0x8
#define GR_TEXFMT_ARGB_8332                      0x8
#define GR_TEXFMT_AYIQ_8422                      0x9
#define GR_TEXFMT_RGB_565                        0xa
#define GR_TEXFMT_ARGB_1555                      0xb
#define GR_TEXFMT_ARGB_4444                      0xc
#define GR_TEXFMT_ALPHA_INTENSITY_88             0xd
#define GR_TEXFMT_AP_88                          0xe
#define GR_TEXFMT_RSVD2                          0xf
#define GR_TEXTABLE_NCC0                         0x0
#define GR_TEXTABLE_NCC1                         0x1
#define GR_TEXTABLE_PALETTE                      0x2
#define GR_NCCTABLE_NCC0                         0x0
#define GR_NCCTABLE_NCC1                         0x1
#define GR_TEXBASE_256                           0x0
#define GR_TEXBASE_128                           0x1
#define GR_TEXBASE_64                            0x2
#define GR_TEXBASE_32_TO_1                       0x3
#define GLIDE3_VERTEX_LAYOUT                     0x1
#define GR_MODE_DISABLE                          0x0
#define GR_MODE_ENABLE                           0x1
#define GR_AA_ORDERED                            0x1
#define GR_ALLOW_MIPMAP_DITHER                   0x2
#define GR_SHAMELESS_PLUG                        0x3
#define GR_VIDEO_SMOOTHING                       0x4
#define GR_WINDOW_COORDS                         0x0
#define GR_CLIP_COORDS                           0x1
#define GLIDE3_EXTRA_STATE                       0x0
#define GR_FLOAT                                 0x0
#define GR_U8                                    0x1
#define GR_PARAM_XY                              0x1
#define GR_PARAM_Z                               0x2
#define GR_PARAM_W                               0x3
#define GR_PARAM_Q                               0x4
#define GR_PARAM_A                               0x10
#define GR_PARAM_A0                              0x10
#define GR_PARAM_A1                              0x11
#define GR_PARAM_A2                              0x12
#define GR_PARAM_A3                              0x13
#define GR_PARAM_A4                              0x14
#define GR_PARAM_A5                              0x15
#define GR_PARAM_A6                              0x16
#define GR_PARAM_A7                              0x17
#define GR_PARAM_RGB                             0x20
#define GR_PARAM_RGB0                            0x20
#define GR_PARAM_RGB1                            0x21
#define GR_PARAM_RGB2                            0x22
#define GR_PARAM_RGB3                            0x23
#define GR_PARAM_RGB4                            0x24
#define GR_PARAM_RGB5                            0x25
#define GR_PARAM_RGB6                            0x26
#define GR_PARAM_RGB7                            0x27
#define GR_PARAM_PARGB                           0x30
#define GR_PARAM_PARGB0                          0x30
#define GR_PARAM_PARGB1                          0x31
#define GR_PARAM_PARGB2                          0x32
#define GR_PARAM_PARGB3                          0x33
#define GR_PARAM_PARGB4                          0x34
#define GR_PARAM_PARGB5                          0x35
#define GR_PARAM_PARGB6                          0x36
#define GR_PARAM_PARGB7                          0x37
#define GR_PARAM_ST0                             0x40
#define GR_PARAM_ST1                             0x41
#define GR_PARAM_ST2                             0x42
#define GR_PARAM_ST3                             0x43
#define GR_PARAM_ST4                             0x44
#define GR_PARAM_ST5                             0x45
#define GR_PARAM_ST6                             0x46
#define GR_PARAM_ST7                             0x47
#define GR_PARAM_Q0                              0x50
#define GR_PARAM_Q1                              0x51
#define GR_PARAM_Q2                              0x52
#define GR_PARAM_Q3                              0x53
#define GR_PARAM_Q4                              0x54
#define GR_PARAM_Q5                              0x55
#define GR_PARAM_Q6                              0x56
#define GR_PARAM_Q7                              0x57
#define GR_PARAM_DISABLE                         0x0
#define GR_PARAM_ENABLE                          0x1
#define GR_VERTEX_XYZ                            0x3
#define GR_VERTEX_XYZW                           0x4
#define GR_COLOR_RGB                             0x3
#define GR_COLOR_RGBA                            0x4
#define GR_TEX_NONE                              0x0
#define GR_TEX_ST                                0x2
#define GR_TEX_STW                               0x3
#define GR_POINTS                                0x0
#define GR_LINE_STRIP                            0x1
#define GR_LINES                                 0x2
#define GR_POLYGON                               0x3
#define GR_TRIANGLE_STRIP                        0x4
#define GR_TRIANGLE_FAN                          0x5
#define GR_TRIANGLES                             0x6
#define GR_BITS_DEPTH                            0x1
#define GR_BITS_RGBA                             0x2
#define GR_FIFO_FULLNESS                         0x3
#define GR_FOG_TABLE_ENTRIES                     0x4
#define GR_GAMMA_TABLE_ENTRIES                   0x5
#define GR_IS_BUSY                               0x6
#define GR_LFB_PIXEL_PIPE                        0x7
#define GR_MAX_TEXTURE_SIZE                      0x8
#define GR_MAX_TEXTURE_ASPECT_RATIO              0x9
#define GR_MEMORY_FB                             0xa
#define GR_MEMORY_TMU                            0xb
#define GR_MEMORY_UMA                            0xc
#define GR_NUM_BOARDS                            0xd
#define GR_NUM_POWER_OF_TWO_TEXTURES             0xe
#define GR_NUM_FB                                0xf
#define GR_NUM_TMU                               0x10
#define GR_PENDING_BUFFERSWAPS                   0x11
#define GR_REVISION_FB                           0x12
#define GR_REVISION_TMU                          0x13
#define GR_STATS_LINES                           0x14
#define GR_STATS_PIXELS_AFUNC_FAIL               0x15
#define GR_STATS_PIXELS_CHROMA_FAIL              0x16
#define GR_STATS_PIXELS_DEPTHFUNC_FAIL           0x17
#define GR_STATS_PIXELS_IN                       0x18
#define GR_STATS_PIXELS_OUT                      0x19
#define GR_STATS_PIXELS                          0x1a
#define GR_STATS_POINTS                          0x1b
#define GR_STATS_TRIANGLES_IN                    0x1c
#define GR_STATS_TRIANGLES_OUT                   0x1d
#define GR_STATS_TRIANGLES                       0x1e
#define GR_SWAP_HISTORY                          0x1f
#define GR_TEXTURE_ALIGN                         0x20
#define GR_VIDEO_POSITION                        0x21
#define GR_VIEWPORT                              0x22
#define GR_WDEPTH_MIN_MAX                        0x23
#define GR_ZDEPTH_MIN_MAX                        0x24
#define GR_EXTENSION                             0xa0
#define GR_HARDWARE                              0xa1
#define GR_RENDERER                              0xa2
#define GR_VENDOR                                0xa3
#define GR_VERSION                               0xa4
#define GR_SSTTYPE_VOODOO                        0x0
#define GR_SSTTYPE_SST96                         0x1
#define GR_SSTTYPE_AT3D                          0x2
#define GR_SSTTYPE_Voodoo2                       0x3
#define GR_VERTEX_X_OFFSET                       0x0
#define GR_VERTEX_Y_OFFSET                       0x1
#define GR_VERTEX_Z_OFFSET                       0x8
#define GR_VERTEX_R_OFFSET                       0x4
#define GR_VERTEX_G_OFFSET                       0x5
#define GR_VERTEX_B_OFFSET                       0x6
#define GR_VERTEX_OOZ_OFFSET                     0x2
#define GR_VERTEX_A_OFFSET                       0x7
#define GR_VERTEX_OOW_OFFSET                     0x3
#define GR_VERTEX_SOW_TMU0_OFFSET                0x9
#define GR_VERTEX_TOW_TMU0_OFFSET                0xa
#define GR_VERTEX_OOW_TMU0_OFFSET                0xb
#define GR_VERTEX_SOW_TMU1_OFFSET                0xc
#define GR_VERTEX_TOW_TMU1_OFFSET                0xd
#define GR_VERTEX_OOW_TMU1_OFFSET                0xe
#define GR_VERTEX_SOW_TMU2_OFFSET                0xf
#define GR_VERTEX_TOW_TMU2_OFFSET                0x10
#define GR_VERTEX_OOW_TMU2_OFFSET                0x11
#define GR_LFB_SRC_FMT_565                       0x0
#define GR_LFB_SRC_FMT_555                       0x1
#define GR_LFB_SRC_FMT_1555                      0x2
#define GR_LFB_SRC_FMT_888                       0x4
#define GR_LFB_SRC_FMT_8888                      0x5
#define GR_LFB_SRC_FMT_565_DEPTH                 0xc
#define GR_LFB_SRC_FMT_555_DEPTH                 0xd
#define GR_LFB_SRC_FMT_1555_DEPTH                0xe
#define GR_LFB_SRC_FMT_ZA16                      0xf
#define GR_LFB_SRC_FMT_RLE16                     0x80
#define GR_PASSTHRU_SHOW_VGA                     0x0
#define GR_PASSTHRU_SHOW_SST1                    0x1
#define GR_HINTTYPE_MIN                          0x0
#define GR_HINT_STWHINT                          0x0
#define GR_HINT_FIFOCHECKHINT                    0x1
#define GR_HINT_FPUPRECISION                     0x2
#define GR_HINT_ALLOW_MIPMAP_DITHER              0x3
#define GR_HINT_LFB_WRITE                        0x4
#define GR_HINT_LFB_PROTECT                      0x5
#define GR_HINT_LFB_RESET                        0x6
#define GR_HINTTYPE_MAX                          0x6
#define GR_HINT_H3DENABLE                        0x6
#define GR_STWHINT_W_DIFF_FBI                    0x1
#define GR_STWHINT_W_DIFF_TMU0                   0x2
#define GR_STWHINT_ST_DIFF_TMU0                  0x4
#define GR_STWHINT_W_DIFF_TMU1                   0x8
#define GR_STWHINT_ST_DIFF_TMU1                  0x10
#define GR_STWHINT_W_DIFF_TMU2                   0x20
#define GR_STWHINT_ST_DIFF_TMU2                  0x40
#define GR_CONTROL_ACTIVATE                      0x1
#define GR_CONTROL_DEACTIVATE                    0x2
#define GR_CONTROL_RESIZE                        0x3
#define GR_CONTROL_MOVE                          0x4
#define GLIDE_NUM_VIRTUAL_TMU                    0x2
#define GR_MPTEXTURECOMBINE_ADD                  0x0
#define GR_MPTEXTURECOMBINE_MULTIPLY             0x1
#define GR_MPTEXTURECOMBINE_DETAIL0              0x2
#define GR_MPTEXTURECOMBINE_DETAIL1              0x3
#define GR_MPTEXTURECOMBINE_TRILINEAR0           0x4
#define GR_MPTEXTURECOMBINE_TRILINEAR1           0x5
#define GR_MPTEXTURECOMBINE_SUBTRACT             0x6
#define GR_REFRESH_60Hz                          0x0
#define GR_REFRESH_70Hz                          0x1
#define GR_REFRESH_72Hz                          0x2
#define GR_REFRESH_75Hz                          0x3
#define GR_REFRESH_80Hz                          0x4
#define GR_REFRESH_90Hz                          0x5
#define GR_REFRESH_100Hz                         0x6
#define GR_REFRESH_85Hz                          0x7
#define GR_REFRESH_120Hz                         0x8
#define GR_REFRESH_NONE                          0xff
#define GR_RESOLUTION_320x200                    0x0
#define GR_RESOLUTION_320x240                    0x1
#define GR_RESOLUTION_400x256                    0x2
#define GR_RESOLUTION_512x384                    0x3
#define GR_RESOLUTION_640x200                    0x4
#define GR_RESOLUTION_640x350                    0x5
#define GR_RESOLUTION_640x400                    0x6
#define GR_RESOLUTION_640x480                    0x7
#define GR_RESOLUTION_800x600                    0x8
#define GR_RESOLUTION_960x720                    0x9
#define GR_RESOLUTION_856x480                    0xa
#define GR_RESOLUTION_512x256                    0xb
#define GR_RESOLUTION_1024x768                   0xc
#define GR_RESOLUTION_1280x1024                  0xd
#define GR_RESOLUTION_1600x1200                  0xe
#define GR_RESOLUTION_400x300                    0xf
#define GR_RESOLUTION_NONE                       0xff
#define GR_RESOLUTION_MIN                        0x0
#define GR_RESOLUTION_MAX                        0xe

/* ---- Functions (abi/glide2x.api) ----------------------------------- */
void GLIDE_API grAADrawLine(const GrVertex *v1, const GrVertex *v2);
void GLIDE_API grAADrawPoint(const GrVertex *pt);
void GLIDE_API grAADrawPolygon(const int nverts, const int ilist[], const GrVertex vlist[]);
void GLIDE_API grAADrawPolygonVertexList(const int nverts, const GrVertex vlist[]);
void GLIDE_API grAADrawTriangle(const GrVertex *a, const GrVertex *b, const GrVertex *c, FxBool ab_antialias, FxBool bc_antialias, FxBool ca_antialias);
void GLIDE_API grAlphaBlendFunction(GrAlphaBlendFnc_t rgb_sf, GrAlphaBlendFnc_t rgb_df, GrAlphaBlendFnc_t alpha_sf, GrAlphaBlendFnc_t alpha_df);
void GLIDE_API grAlphaCombine(GrCombineFunction_t function, GrCombineFactor_t factor, GrCombineLocal_t local, GrCombineOther_t other, FxBool invert);
void GLIDE_API grAlphaControlsITRGBLighting(FxBool enable);
void GLIDE_API grAlphaTestFunction(GrCmpFnc_t function);
void GLIDE_API grAlphaTestReferenceValue(GrAlpha_t value);
void GLIDE_API grBufferClear(GrColor_t color, GrAlpha_t alpha, FxU16 depth);
int GLIDE_API grBufferNumPending(void);
void GLIDE_API grBufferSwap(int swap_interval);
void GLIDE_API grCheckForRoom(FxI32 n);
void GLIDE_API grChromakeyMode(GrChromakeyMode_t mode);
void GLIDE_API grChromakeyValue(GrColor_t value);
void GLIDE_API grClipWindow(FxU32 minx, FxU32 miny, FxU32 maxx, FxU32 maxy);
void GLIDE_API grColorCombine(GrCombineFunction_t function, GrCombineFactor_t factor, GrCombineLocal_t local, GrCombineOther_t other, FxBool invert);
void GLIDE_API grColorMask(FxBool rgb, FxBool a);
void GLIDE_API grConstantColorValue4(float a, float r, float g, float b);
void GLIDE_API grConstantColorValue(GrColor_t value);
void GLIDE_API grCullMode(GrCullMode_t mode);
void GLIDE_API grDepthBiasLevel(FxI16 level);
void GLIDE_API grDepthBufferFunction(GrCmpFnc_t function);
void GLIDE_API grDepthBufferMode(GrDepthBufferMode_t mode);
void GLIDE_API grDepthMask(FxBool mask);
void GLIDE_API grDisableAllEffects(void);
void GLIDE_API grDitherMode(GrDitherMode_t mode);
void GLIDE_API grDrawLine(const GrVertex *v1, const GrVertex *v2);
void GLIDE_API grDrawPlanarPolygon(int nverts, const int ilist[], const GrVertex vlist[]);
void GLIDE_API grDrawPlanarPolygonVertexList(int nverts, const GrVertex vlist[]);
void GLIDE_API grDrawPoint(const GrVertex *pt);
void GLIDE_API grDrawPolygon(int nverts, const int ilist[], const GrVertex vlist[]);
void GLIDE_API grDrawPolygonVertexList(int nverts, const GrVertex vlist[]);
void GLIDE_API grDrawTriangle(const GrVertex *a, const GrVertex *b, const GrVertex *c);
void GLIDE_API grErrorSetCallback(GrErrorCallbackFnc_t fnc);
void GLIDE_API grFogColorValue(GrColor_t fogcolor);
void GLIDE_API grFogMode(GrFogMode_t mode);
void GLIDE_API grFogTable(const GrFog_t ft[]);
void GLIDE_API grGammaCorrectionValue(float value);
void GLIDE_API grGlideGetState(GrState *state);
void GLIDE_API grGlideGetVersion(char version[80]);
void GLIDE_API grGlideInit(void);
void GLIDE_API grGlideSetState(const GrState *state);
void GLIDE_API grGlideShamelessPlug(const FxBool on);
void GLIDE_API grGlideShutdown(void);
void GLIDE_API grHints(GrHint_t hintType, FxU32 hintMask);
void GLIDE_API grLfbConstantAlpha(GrAlpha_t alpha);
void GLIDE_API grLfbConstantDepth(FxU16 depth);
FxBool GLIDE_API grLfbLock(GrLock_t type, GrBuffer_t buffer, GrLfbWriteMode_t writeMode, GrOriginLocation_t origin, FxBool pixelPipeline, GrLfbInfo_t *info);
FxBool GLIDE_API grLfbReadRegion(GrBuffer_t src_buffer, FxU32 src_x, FxU32 src_y, FxU32 src_width, FxU32 src_height, FxU32 dst_stride, void *dst_data);
FxBool GLIDE_API grLfbUnlock(GrLock_t type, GrBuffer_t buffer);
void GLIDE_API grLfbWriteColorFormat(GrColorFormat_t colorFormat);
void GLIDE_API grLfbWriteColorSwizzle(FxBool swizzleBytes, FxBool swapWords);
FxBool GLIDE_API grLfbWriteRegion(GrBuffer_t dst_buffer, FxU32 dst_x, FxU32 dst_y, GrLfbSrcFmt_t src_format, FxU32 src_width, FxU32 src_height, FxI32 src_stride, void *src_data);
void GLIDE_API grRenderBuffer(GrBuffer_t buffer);
void GLIDE_API grResetTriStats();
void GLIDE_API grSplash(float x, float y, float width, float height, FxU32 frame);
void GLIDE_API grSstConfigPipeline(GrChipID_t chip, FxU32 reg, FxU32 value);
FxBool GLIDE_API grSstControl(FxU32 code);
void GLIDE_API grSstIdle(void);
FxBool GLIDE_API grSstIsBusy(void);
void GLIDE_API grSstOrigin(GrOriginLocation_t origin);
void GLIDE_API grSstPerfStats(GrSstPerfStats_t *pStats);
FxBool GLIDE_API grSstQueryBoards(GrHwConfiguration *hwconfig);
FxBool GLIDE_API grSstQueryHardware(GrHwConfiguration *hwconfig);
void GLIDE_API grSstResetPerfStats(void);
FxU32 GLIDE_API grSstScreenHeight(void);
FxU32 GLIDE_API grSstScreenWidth(void);
void GLIDE_API grSstSelect(int which_sst);
FxU32 GLIDE_API grSstStatus(void);
FxU32 GLIDE_API grSstVideoLine(void);
void GLIDE_API grSstVidMode(FxU32 whichSst, void *vidTimings);
FxBool GLIDE_API grSstVRetraceOn(void);
void GLIDE_API grSstWinClose(void);
FxBool GLIDE_API grSstWinOpen(FxU32 hWnd, GrScreenResolution_t screen_resolution, GrScreenRefresh_t refresh_rate, GrColorFormat_t color_format, GrOriginLocation_t origin_location, int nColBuffers, int nAuxBuffers);
FxU32 GLIDE_API grTexCalcMemRequired(GrLOD_t lodmin, GrLOD_t lodmax, GrAspectRatio_t aspect, GrTextureFormat_t fmt);
void GLIDE_API grTexClampMode(GrChipID_t tmu, GrTextureClampMode_t s_clampmode, GrTextureClampMode_t t_clampmode);
void GLIDE_API grTexCombine(GrChipID_t tmu, GrCombineFunction_t rgb_function, GrCombineFactor_t rgb_factor, GrCombineFunction_t alpha_function, GrCombineFactor_t alpha_factor, FxBool rgb_invert, FxBool alpha_invert);
void GLIDE_API grTexCombineFunction(GrChipID_t tmu, GrTextureCombineFnc_t fnc);
void GLIDE_API grTexDetailControl(GrChipID_t tmu, int lod_bias, FxU8 detail_scale, float detail_max);
void GLIDE_API grTexDownloadMipMap(GrChipID_t tmu, FxU32 startAddress, FxU32 evenOdd, GrTexInfo *info);
void GLIDE_API grTexDownloadMipMapLevel(GrChipID_t tmu, FxU32 startAddress, GrLOD_t thisLod, GrLOD_t largeLod, GrAspectRatio_t aspectRatio, GrTextureFormat_t format, FxU32 evenOdd, void *data);
void GLIDE_API grTexDownloadMipMapLevelPartial(GrChipID_t tmu, FxU32 startAddress, GrLOD_t thisLod, GrLOD_t largeLod, GrAspectRatio_t aspectRatio, GrTextureFormat_t format, FxU32 evenOdd, void *data, int start, int end);
void GLIDE_API grTexDownloadTable(GrChipID_t tmu, GrTexTable_t type, void *data);
void GLIDE_API grTexDownloadTablePartial(GrChipID_t tmu, GrTexTable_t type, void *data, int start, int end);
void GLIDE_API grTexFilterMode(GrChipID_t tmu, GrTextureFilterMode_t minfilter_mode, GrTextureFilterMode_t magfilter_mode);
void GLIDE_API grTexLodBiasValue(GrChipID_t tmu, float bias);
FxU32 GLIDE_API grTexMaxAddress(GrChipID_t tmu);
FxU32 GLIDE_API grTexMinAddress(GrChipID_t tmu);
void GLIDE_API grTexMipMapMode(GrChipID_t tmu, GrMipMapMode_t mode, FxBool lodBlend);
void GLIDE_API grTexMultibase(GrChipID_t tmu, FxBool enable);
void GLIDE_API grTexMultibaseAddress(GrChipID_t tmu, GrTexBaseRange_t range, FxU32 startAddress, FxU32 evenOdd, GrTexInfo *info);
void GLIDE_API grTexNCCTable(GrChipID_t tmu, GrNCCTable_t table);
void GLIDE_API grTexSource(GrChipID_t tmu, FxU32 startAddress, FxU32 evenOdd, GrTexInfo *info);
FxU32 GLIDE_API grTexTextureMemRequired(FxU32 evenOdd, GrTexInfo *info);
void GLIDE_API grTriStats(FxU32 *trisProcessed, FxU32 *trisDrawn);
FxBool GLIDE_API gu3dfGetInfo(const char *filename, Gu3dfInfo *info);
FxBool GLIDE_API gu3dfLoad(const char *filename, Gu3dfInfo *data);
void GLIDE_API guAADrawTriangleWithClip(const GrVertex *a, const GrVertex *b, const GrVertex *c);
void GLIDE_API guAlphaSource(GrAlphaSource_t mode);
void GLIDE_API guColorCombineFunction(GrColorCombineFnc_t fnc);
void GLIDE_API guDrawPolygonVertexListWithClip(int nverts, const GrVertex vlist[]);
void GLIDE_API guDrawTriangleWithClip(const GrVertex *a, const GrVertex *b, const GrVertex *c);
int GLIDE_API guEncodeRLE16(void *dst, void *src, FxU32 width, FxU32 height);
FxU16 GLIDE_API guEndianSwapBytes(FxU16 value);
FxU32 GLIDE_API guEndianSwapWords(FxU32 value);
FxBool GLIDE_API guFbReadRegion(int src_x, int src_y, int w, int h, void *dst, int strideInBytes);
FxBool GLIDE_API guFbWriteRegion(int dst_x, int dst_y, int w, int h, const void *src, int strideInBytes);
void GLIDE_API guFogGenerateExp2(GrFog_t fogtable[], float density);
void GLIDE_API guFogGenerateExp(GrFog_t fogtable[], float density);
void GLIDE_API guFogGenerateLinear(GrFog_t fogtable[], float nearZ, float farZ);
float GLIDE_API guFogTableIndexToW(int i);
void GLIDE_API guMovieSetName(const char *name);
void GLIDE_API guMovieStart(void);
void GLIDE_API guMovieStop(void);
void GLIDE_API guMPDrawTriangle(const GrVertex *a, const GrVertex *b, const GrVertex *c);
void GLIDE_API guMPInit(void);
void GLIDE_API guMPTexCombineFunction(GrMPTextureCombineFnc_t tc);
void GLIDE_API guMPTexSource(GrChipID_t virtual_tmu, GrMipMapId_t mmid);
GrMipMapId_t GLIDE_API guTexAllocateMemory(GrChipID_t tmu, FxU8 odd_even_mask, int width, int height, GrTextureFormat_t fmt, GrMipMapMode_t mm_mode, GrLOD_t smallest_lod, GrLOD_t largest_lod, GrAspectRatio_t aspect, GrTextureClampMode_t s_clamp_mode, GrTextureClampMode_t t_clamp_mode, GrTextureFilterMode_t minfilter_mode, GrTextureFilterMode_t magfilter_mode, float lod_bias, FxBool trilinear);
FxBool GLIDE_API guTexChangeAttributes(GrMipMapId_t mmid, int width, int height, GrTextureFormat_t fmt, GrMipMapMode_t mm_mode, GrLOD_t smallest_lod, GrLOD_t largest_lod, GrAspectRatio_t aspect, GrTextureClampMode_t s_clamp_mode, GrTextureClampMode_t t_clamp_mode, GrTextureFilterMode_t minFilterMode, GrTextureFilterMode_t magFilterMode);
void GLIDE_API guTexCombineFunction(GrChipID_t tmu, GrTextureCombineFnc_t fnc);
FxU16 * GLIDE_API guTexCreateColorMipMap(void);
void GLIDE_API guTexDownloadMipMap(GrMipMapId_t mmid, const void *src, const GuNccTable *table);
void GLIDE_API guTexDownloadMipMapLevel(GrMipMapId_t mmid, GrLOD_t lod, const void **src);
GrMipMapId_t GLIDE_API guTexGetCurrentMipMap(GrChipID_t tmu);
GrMipMapInfo * GLIDE_API guTexGetMipMapInfo(GrMipMapId_t mmid);
FxU32 GLIDE_API guTexMemQueryAvail(GrChipID_t tmu);
void GLIDE_API guTexMemReset(void);
void GLIDE_API guTexSource(GrMipMapId_t id);

#ifdef __cplusplus
}
#endif
#endif /* MGAGLIDE_GLIDE2_H */
