#!/usr/bin/env python3
"""Write docs/api-coverage.md: every Glide 2.x function with its tier,
which acceptance games import it, its status, and (when call traces are
given) how often each game actually called it.

  coverage.py [gta=TRACE] [sr=TRACE]
"""
import collections
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "tools", "trace"))
from api import load_api  # noqa: E402

GAMES = {"g": "GTA", "s": "Screamer Rally"}


def trace_counts(path):
    import trdump
    api = trdump.api_table()
    c = collections.Counter()
    for op, _a, _b in trdump.records(path):
        if op < trdump.OP_PSEUDO:
            c[api[op]["name"]] += 1
    return c


def main(argv):
    funcs = load_api(os.path.join(ROOT, "abi", "glide2x.api"))
    traces = {}
    for arg in argv[1:]:
        k, p = arg.split("=", 1)
        traces[k] = trace_counts(p)
    status = collections.Counter(f.status for f in funcs)
    out = ["# Glide API coverage", "",
           "Generated by `tools/abi/coverage.py` from `abi/glide2x.api`%s." %
           (" and call traces of " + ", ".join(sorted(traces)) if traces else ""), "",
           "Tier 1 is needed to start, tier 2 is state and texturing the games use, tier 3",
           "was a logged stub first. Status: `partial` is implemented (with the",
           "limitations noted in `docs/combine-coverage.md` and `docs/reference-gaps.md`),",
           "`stub` logs its first call and does nothing.", "",
           "| Status | Functions |", "|---|---|"]
    for s in ("done", "partial", "stub"):
        out.append("| %s | %d |" % (s, status.get(s, 0)))
    out += ["", "| Function | Tier | Imported by | Status |" + "".join(" Calls (%s) |" % k for k in sorted(traces)),
            "|---|---|---|---|" + "---|" * len(traces)]
    for f in sorted(funcs, key=lambda f: (f.tier, f.name)):
        used = ", ".join(GAMES[c] for c in f.used if c in GAMES) or "-"
        row = "| `%s` | %d | %s | %s |" % (f.name, f.tier, used, f.status)
        for k in sorted(traces):
            row += " %s |" % (traces[k].get(f.name, "") or "")
        out.append(row)
    out.append("")
    open(os.path.join(ROOT, "docs", "api-coverage.md"), "w").write("\n".join(out))


if __name__ == "__main__":
    main(sys.argv)
