#!/usr/bin/env python3
"""Generate include/glide/glide2.h from the ABI tables.

Inputs: abi/constants.tsv (interface constants), abi/types.h.frag
(project-authored type and structure definitions) and abi/glide2x.api
(function table). The output is the project's own clean-room header.
"""
import sys

from api import load_api


def main(root, out):
    consts = []
    for line in open(root + "/abi/constants.tsv"):
        if line.startswith("#") or not line.strip():
            continue
        name, value, _src = line.rstrip("\n").split("\t")
        consts.append((name, value))
    frag = open(root + "/abi/types.h.frag").read()
    skip = {"GLIDE_NUM_TMU", "MAX_NUM_SST", "GLIDE_STATE_PAD_SIZE"}
    o = []
    w = o.append
    w("/* glide2.h - MGA-Glide clean-room Glide 2.x interface.")
    w(" * GENERATED by tools/abi/gen_header.py from abi/ - do not edit.")
    w(" * Glide is a trademark of its owner; see the project README. */")
    w("#ifndef MGAGLIDE_GLIDE2_H")
    w("#define MGAGLIDE_GLIDE2_H")
    w("")
    w("#if defined(__WATCOMC__)")
    w("#  define GLIDE_API __stdcall")
    w("#elif defined(__GNUC__) && defined(__i386__)")
    w("#  define GLIDE_API __attribute__((stdcall))")
    w("#else")
    w("#  define GLIDE_API")
    w("#endif")
    w("")
    w("#ifdef __cplusplus")
    w('extern "C" {')
    w("#endif")
    w("")
    w(frag.rstrip())
    w("")
    w("/* ---- Constants (abi/constants.tsv) --------------------------------- */")
    for name, value in consts:
        if name in skip:
            continue
        w("#define %-40s %s" % (name, value))
    w("")
    w("/* ---- Functions (abi/glide2x.api) ----------------------------------- */")
    for f in load_api(root + "/abi/glide2x.api"):
        w("%s GLIDE_API %s(%s);" % (f.ret, f.name, f.args))
    w("")
    w("#ifdef __cplusplus")
    w("}")
    w("#endif")
    w("#endif /* MGAGLIDE_GLIDE2_H */")
    with open(out, "w") as fh:
        fh.write("\n".join(o) + "\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
