#!/usr/bin/env python3
"""Generate the call-trace glue from build/gen/api.json (see docs/trace.md):

  thunks.c      runtime: one exported thunk per Glide function. It records
                the call (when tracing, outermost calls only) and calls
                impl_<name>, the implementation defined with GR_ENTRY.
  replay_gen.c  GLPLAY: rebuilds each recorded call and makes it through
                the function table of the OVL under test.

Pointer parameters need a rule (DEEP below); an unknown pointer type stops
generation, so nothing is traced as a bare address by accident.
"""
import json
import os
import sys

# kind, C size expression (in terms of the parameters) where needed.
#   vtx      one GrVertex, through the vertex cache
#   bytes    a blob of <expr> bytes (NULL pointers are recorded as NULL)
#   out      output buffer: not recorded; the replayer passes scratch space
#   str      NUL-terminated string
#   srcpp    const void ** advanced by the callee: blob of <expr> bytes
#   none     not replayable (callbacks, file names): passed as NULL
DEEP = {
    ("grAADrawPolygon", "ilist"): ("bytes", "nverts * 4"),
    ("grAADrawPolygon", "vlist"): ("bytes", "tr_max_index(ilist, nverts) * 60u"),
    ("grDrawPolygon", "ilist"): ("bytes", "nverts * 4"),
    ("grDrawPolygon", "vlist"): ("bytes", "tr_max_index(ilist, nverts) * 60u"),
    ("grDrawPlanarPolygon", "ilist"): ("bytes", "nverts * 4"),
    ("grDrawPlanarPolygon", "vlist"): ("bytes", "tr_max_index(ilist, nverts) * 60u"),
    ("grAADrawPolygonVertexList", "vlist"): ("bytes", "nverts * 60u"),
    ("grDrawPolygonVertexList", "vlist"): ("bytes", "nverts * 60u"),
    ("grDrawPlanarPolygonVertexList", "vlist"): ("bytes", "nverts * 60u"),
    ("guDrawPolygonVertexListWithClip", "vlist"): ("bytes", "nverts * 60u"),
    ("grErrorSetCallback", "fnc"): ("none", None),
    ("grFogTable", "ft"): ("bytes", "64u"),
    ("grGlideGetState", "state"): ("out", None),
    ("grGlideGetVersion", "version"): ("out", None),
    ("grGlideSetState", "state"): ("bytes", "sizeof(GrState)"),
    ("grLfbLock", "info"): ("out", None),
    ("grLfbReadRegion", "dst_data"): ("out", None),
    ("grLfbWriteRegion", "src_data"): ("bytes", "tr_region_bytes(src_width, src_height, src_stride, tr_lfb_src_bpp(src_format))"),
    ("grSstPerfStats", "pStats"): ("out", None),
    ("grSstQueryBoards", "hwconfig"): ("out", None),
    ("grSstQueryHardware", "hwconfig"): ("out", None),
    ("grSstVidMode", "vidTimings"): ("none", None),
    ("grTexDownloadMipMap", "info"): ("texinfo_data", None),
    ("grTexDownloadMipMapLevel", "data"): ("bytes", "tex_level_data_bytes(thisLod, aspectRatio, format)"),
    ("grTexDownloadMipMapLevelPartial", "data"): ("bytes", "tr_partial_bytes(thisLod, aspectRatio, format, start, end)"),
    ("grTexDownloadTable", "data"): ("bytes", "tr_table_bytes(type)"),
    ("grTexDownloadTablePartial", "data"): ("bytes", "tr_table_bytes(type)"),
    ("grTexMultibaseAddress", "info"): ("bytes", "sizeof(GrTexInfo)"),
    ("grTexSource", "info"): ("bytes", "sizeof(GrTexInfo)"),
    ("grTexTextureMemRequired", "info"): ("bytes", "sizeof(GrTexInfo)"),
    ("grTriStats", "trisProcessed"): ("out", None),
    ("grTriStats", "trisDrawn"): ("out", None),
    ("gu3dfGetInfo", "filename"): ("str", None),
    ("gu3dfGetInfo", "info"): ("out", None),
    ("gu3dfLoad", "filename"): ("str", None),
    ("gu3dfLoad", "data"): ("out", None),
    ("guEncodeRLE16", "dst"): ("out", None),
    ("guEncodeRLE16", "src"): ("bytes", "(uint32_t)width * (uint32_t)height * 2u"),
    ("guFbReadRegion", "dst"): ("out", None),
    ("guFbWriteRegion", "src"): ("bytes", "tr_region_bytes(w, h, strideInBytes, 2)"),
    ("guFogGenerateExp2", "fogtable"): ("out", None),
    ("guFogGenerateExp", "fogtable"): ("out", None),
    ("guFogGenerateLinear", "fogtable"): ("out", None),
    ("guMovieSetName", "name"): ("str", None),
    ("guTexDownloadMipMap", "src"): ("bytes", "tr_gu_src_bytes(mmid)"),
    ("guTexDownloadMipMap", "table"): ("bytes", "sizeof(GuNccTable)"),
    ("guTexDownloadMipMapLevel", "src"): ("srcpp", "tr_gu_level_bytes(mmid, lod)"),
}


def kind_of(f, t, n):
    k = DEEP.get((f["name"], n))
    if k:
        return k
    if t.replace(" ", "") == "constGrVertex*":
        return ("vtx", None)
    if "(" in t or "(*" in n:
        return ("none", None)
    if "*" in t or "[" in t:
        sys.exit("gen_trace: no trace rule for %s(%s %s)" % (f["name"], t, n))
    return ("scalar", None)


def is_float(t):
    return t.strip() == "float"


def main(outdir):
    api = json.load(open(os.path.join(outdir, "api.json")))
    th = ["/* GENERATED by tools/abi/gen_trace.py - do not edit. */",
          '#include "glide/entry.h"', '#include "trace/trace.h"', '#include "tex/texfmt.h"',
          "#include <string.h>", ""]
    rp = ["/* GENERATED by tools/abi/gen_trace.py - do not edit. */",
          '#include "replay.h"', ""]
    rp.append("int rp_dispatch(int op, const uint32_t *A, void *const *B, uint32_t *ret)")
    rp.append("{")
    rp.append("    switch (op) {")
    for f in api:
        name, ret, params = f["name"], f["ret"].strip(), f["params"]
        plist = ", ".join("%s %s" % (t, n) for t, n in params) or "void"
        th.append("%s GLIDE_API impl_%s(%s);" % (ret, name, plist))
        kinds = [kind_of(f, t, n) for t, n in params]
        # Thunk.
        th.append("%s GR_EXPORT GLIDE_API %s(%s)" % (ret, name, plist))
        th.append("{")
        if ret != "void":
            th.append("    %s r;" % ret)
        th.append("    if (mg_trace_on && !mg_trace_depth) {")
        if name == "grLfbUnlock":
            th.append("        tr_lfb_unlock_spans(type, buffer);")
        nw = len(params)
        th.append("        uint32_t tr_args_[%d];" % max(nw, 1))
        for i, (t, n) in enumerate(params):
            if is_float(t):
                th.append("        memcpy(&tr_args_[%d], &%s, 4);" % (i, n))
            else:
                th.append("        tr_args_[%d] = (uint32_t)%s;" % (i, n))
        nb = sum(1 for k in kinds if k[0] not in ("scalar", "out", "none"))
        nb += sum(1 for k in kinds if k[0] == "texinfo_data")     # struct + data
        th.append("        tr_begin(MGA_API_%s, tr_args_, %d, %d);" % (name, nw, nb))
        for (t, n), (k, expr) in zip(params, kinds):
            if k == "vtx":
                th.append("        tr_vertex(%s);" % n)
            elif k == "bytes":
                th.append("        tr_blob(%s, %s ? (uint32_t)(%s) : 0u);" % (n, n, expr))
            elif k == "str":
                th.append("        tr_blob(%s, %s ? (uint32_t)strlen(%s) + 1u : 0u);" % (n, n, n))
            elif k == "srcpp":
                th.append("        tr_blob(%s ? *%s : 0, %s && *%s ? (uint32_t)(%s) : 0u);" % (n, n, n, n, expr))
            elif k == "texinfo_data":
                th.append("        tr_blob(%s, %s ? (uint32_t)sizeof(GrTexInfo) : 0u);" % (n, n))
                th.append("        tr_blob(%s ? %s->data : 0, %s ? tr_texinfo_bytes(%s) : 0u);" % (n, n, n, n))
        th.append("        tr_end();")
        th.append("    }")
        th.append("    mg_trace_depth++;")
        call = "impl_%s(%s)" % (name, ", ".join(n for _t, n in params))
        th.append("    %s%s;" % ("r = " if ret != "void" else "", call))
        th.append("    mg_trace_depth--;")
        if ret != "void":
            th.append("    return r;")
        th.append("}")
        th.append("")
        # Replay.
        rp.append("    case %d: { /* %s */" % (f["id"], name))
        args, bi = [], 0
        pre = []
        for i, ((t, n), (k, _e)) in enumerate(zip(params, kinds)):
            if k == "scalar":
                args.append("rp_f(A[%d])" % i if is_float(t) else "(%s)A[%d]" % (t, i))
            elif k == "out":
                args.append("(%s)rp_scratch" % t)
            elif k == "none":
                args.append("(%s)0" % t)
            elif k == "srcpp":
                pre.append("const void *p%d = B[%d];" % (i, bi))
                args.append("&p%d" % i)
                bi += 1
            elif k == "texinfo_data":
                pre.append("GrTexInfo ti%d;" % i)
                pre.append("if (B[%d]) { ti%d = *(const GrTexInfo *)B[%d]; ti%d.data = B[%d]; }" % (bi, i, bi, i, bi + 1))
                args.append("B[%d] ? &ti%d : (GrTexInfo *)0" % (bi, i))
                bi += 2
            else:
                args.append("(%s)B[%d]" % (t, bi))
                bi += 1
        for p in pre:
            rp.append("        " + p)
        call = "gl.%s(%s)" % (name, ", ".join(args))
        if ret == "void":
            rp.append("        %s;" % call)
        elif ret == "float":
            rp.append("        { float v = %s; memcpy(ret, &v, 4); }" % call)
        else:
            rp.append("        *ret = (uint32_t)%s;" % call)
        rp.append("        return 0; }")
    rp += ["    default: return -1;", "    }", "}", ""]
    # GLTRACE.OVL: the same recorders, forwarding to the retail runtime.
    px = ["/* GENERATED by tools/abi/gen_trace.py - do not edit.",
          " * GLTRACE.OVL exports: record, then call the retail runtime. */",
          '#include "glide/entry.h"', '#include "trace/trace.h"', '#include "proxy/proxy.h"',
          '#include "tex/texfmt.h"', "#include <string.h>", ""]
    for f in api:
        name, ret, params = f["name"], f["ret"].strip(), f["params"]
        plist = ", ".join("%s %s" % (t, n) for t, n in params) or "void"
        args = ", ".join(n for _t, n in params)
        px.append("%s GR_EXPORT GLIDE_API %s(%s)" % (ret, name, plist))
        px.append("{")
        if ret != "void":
            px.append("    %s r;" % ret)
        if name == "grGlideInit":
            px.append("    px_init();")
        px.append("    if (!px_loaded)")
        px.append("        px_load();")
        px.append("    if (!px.%s) { px_missing(%d); %s}" % (name, f["id"], "return (%s)0; " % ret if ret != "void" else "return; "))
        # record: identical to the runtime thunk body
        start = th.index("%s GR_EXPORT GLIDE_API %s(%s)" % (ret, name, plist))
        body = []
        k = start + 2 + (1 if ret != "void" else 0)
        while not th[k].startswith("    mg_trace_depth++;"):
            body.append(th[k])
            k += 1
        for line in body:
            px.append(line.replace("tr_lfb_unlock_spans(type, buffer);", "px_lfb_unlock(type, buffer);"))
        if name == "grLfbLock":
            px.append("    r = px_lfb_lock(%s);" % args)
        elif name == "grLfbUnlock":
            px.append("    r = px_lfb_unlock_forward(%s);" % args)
        else:
            px.append("    %spx.%s(%s);" % ("r = " if ret != "void" else "", name, args))
        if name == "guTexAllocateMemory":
            px.append("    px_gu_alloc(r, %s);" % args)
        if name == "grBufferSwap":
            px.append("    px_frame();")
        if name == "grGlideShutdown":
            px.append("    px_shutdown();")
        if ret != "void":
            px.append("    return r;")
        px.append("}")
        px.append("")
    for fn, text in (("thunks.c", "\n".join(th)), ("replay_gen.c", "\n".join(rp)),
                     ("proxy_thunks.c", "\n".join(px))):
        path = os.path.join(outdir, fn)
        old = open(path).read() if os.path.exists(path) else None
        if old != text:
            open(path, "w").write(text)


if __name__ == "__main__":
    main(sys.argv[1])
