#!/usr/bin/env python3
"""Generate the runtime's API glue from abi/glide2x.api into build/gen/:

  api_ids.h    enum MGA_API_<name> ids and MGA_API_COUNT
  api_names.h  name table declaration;  api_names.c  the table itself
  stubs.c      a logged, harmless definition for every function whose
               status is "stub" (implemented functions live in src/)
  exports.lnk  wlink EXPORT directives (one per function)
  api.json     machine-readable table for the tracer and replayer tools
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from api import load_api  # noqa: E402


def default_return(ret):
    r = ret.strip()
    if r == "void":
        return None
    if r == "float":
        return "0.0f"
    if r == "FxBool":
        return "FXFALSE"
    if "*" in r or r in ("GrProc",):
        return "0"
    return "0"


def main(root, outdir):
    funcs = load_api(os.path.join(root, "abi", "glide2x.api"))
    os.makedirs(outdir, exist_ok=True)

    def write(name, text):
        path = os.path.join(outdir, name)
        old = open(path).read() if os.path.exists(path) else None
        if old != text:
            with open(path, "w") as f:
                f.write(text)

    ids = ["/* GENERATED by tools/abi/gen_exports.py - do not edit. */",
           "#ifndef MGA_API_IDS_H", "#define MGA_API_IDS_H", "enum {"]
    for i, f in enumerate(funcs):
        ids.append("    MGA_API_%s = %d," % (f.name, i))
    ids += ["    MGA_API_COUNT = %d" % len(funcs), "};", "#endif", ""]
    write("api_ids.h", "\n".join(ids))

    write("api_names.h", "/* GENERATED */\n#ifndef MGA_API_NAMES_H\n#define MGA_API_NAMES_H\n"
          "extern const char *const mga_api_names[];\n"
          "extern const unsigned char mga_api_argbytes[];\n#endif\n")
    names = ["/* GENERATED by tools/abi/gen_exports.py - do not edit. */",
             '#include "api_names.h"', "const char *const mga_api_names[] = {"]
    names += ['    "%s",' % f.name for f in funcs] + ["};",
              "const unsigned char mga_api_argbytes[] = {"]
    names += ["    %d," % f.nbytes for f in funcs] + ["};", ""]
    write("api_names.c", "\n".join(names))

    st = ["/* GENERATED by tools/abi/gen_exports.py - do not edit.",
          " * Logged stubs for functions whose status in abi/glide2x.api is 'stub'. */",
          '#include "glide/entry.h"', ""]
    for f in funcs:
        if f.status != "stub":
            continue
        params = ", ".join("%s %s" % (t, n) for t, n in f.params) or "void"
        st.append("GR_ENTRY(%s, %s, (%s))" % (f.ret, f.name, params))
        st.append("{")
        for _t, n in f.params:
            st.append("    (void)%s;" % n)
        st.append("    mg_stub_hit(MGA_API_%s);" % f.name)
        d = default_return(f.ret)
        if d is not None:
            st.append("    return %s;" % d)
        st.append("}")
        st.append("")
    write("stubs.c", "\n".join(st))

    ga = ["/* GENERATED by tools/abi/gen_exports.py - do not edit.",
          " * Glide function table used by test programs: filled from an OVL",
          " * loaded with leload, or from the statically linked runtime. */",
          "#ifndef MGA_GLAPI_H", "#define MGA_GLAPI_H", '#include "glide/glide2.h"',
          "typedef struct {"]
    for f in funcs:
        params = ", ".join(t for t, _n in f.params) or "void"
        ga.append("    %s (GLIDE_API *%s)(%s);" % (f.ret, f.name, params))
    ga += ["} glapi_t;", "#define GLAPI_COUNT %d" % len(funcs),
           "extern const char *const glapi_decorated[GLAPI_COUNT];", "#endif", ""]
    write("glapi.h", "\n".join(ga))
    gd = ["/* GENERATED by tools/abi/gen_exports.py - do not edit. */", '#include "glapi.h"',
          "const char *const glapi_decorated[GLAPI_COUNT] = {"]
    gd += ['    "%s",' % f.decorated for f in funcs] + ["};", ""]
    write("glapi_names.c", "\n".join(gd))

    write("exports.lnk", "".join("export '%s'\n" % f.decorated for f in funcs))
    write("api.json", json.dumps([dict(id=i, name=f.name, ret=f.ret, params=f.params,
                                       nbytes=f.nbytes, tier=f.tier, status=f.status)
                                  for i, f in enumerate(funcs)], indent=1))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
