#!/usr/bin/env python3
"""Write docs/combine-coverage.md from the last `run.py check t13` result of
each card (out/conform/summary-<card>.json) and the manifest's cell names."""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CARDS = ("g100", "g200")


def load(card):
    p = os.path.join(ROOT, "out", "conform", "summary-%s.json" % card)
    if not os.path.exists(p):
        return None
    d = json.load(open(p))
    return d.get("t13", {}).get("frames")


def main():
    man = json.load(open(os.path.join(ROOT, "tests", "conform", "manifest.json")))["t13"]
    res = {c: load(c) for c in CARDS}
    cards = [c for c in CARDS if res[c]]
    out = ["# Combine coverage", "",
           "Generated by `tools/conform/coverage.py` from conformance test t13, which draws",
           "each combine state on the emulated Matrox card and on the retail Voodoo runtime.",
           "", "- **exact**: matches the Voodoo within the conformance tolerance.",
           "- **approx**: the chip cannot express it; the nearest form is drawn and",
           "  `MGA-DEGRADE` is logged once per state.", ""]
    for fn, title in (("t13_0.png", "Colour combine (gu presets, then raw forms)"),
                      ("t13_1.png", "Alpha sources, blended")):
        names = man["frames"][fn]["cells"]["names"]
        out += ["## " + title, "", "| # | State |" + "".join(" %s |" % c.upper() for c in cards),
                "|---|---|" + "---|" * len(cards)]
        for i, name in enumerate(names):
            row = "| %d | %s |" % (i, name)
            for c in cards:
                cell = res[c][fn]["cells"][str(i)]
                cls = "exact" if cell["ok"] else ("approx" if cell["approx"] else "**FAIL**")
                row += " %s |" % cls
            out.append(row)
        out.append("")
    out += ["Approximate cells: " + man.get("why", "") + ".", ""]
    open(os.path.join(ROOT, "docs", "combine-coverage.md"), "w").write("\n".join(out))


if __name__ == "__main__":
    main()
