#!/usr/bin/env python3
"""Write docs/combine-coverage.md from the last `run.py check t13` result
(out/conform/summary.json) and the manifest's cell names."""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def main():
    man = json.load(open(os.path.join(ROOT, "tests", "conform", "manifest.json")))["t13"]
    res = json.load(open(os.path.join(ROOT, "out", "conform", "summary.json")))["t13"]["frames"]
    out = ["# Combine coverage on the G100", "",
           "Generated by `tools/conform/coverage.py` from conformance test t13, which draws",
           "each combine state on the emulated G100 and on the retail Voodoo runtime.",
           "", "- **exact**: matches the Voodoo within the conformance tolerance.",
           "- **approx**: the G100 cannot express it; the nearest form is drawn and",
           "  `MGA-DEGRADE` is logged once per state. On the G200 the specular add and",
           "  native blending cover most of these.", ""]
    why = man.get("why", "")
    for fn, title in (("t13_0.png", "Colour combine (gu presets, then raw forms)"),
                      ("t13_1.png", "Alpha sources, blended (compared box-filtered: G100 stipple)")):
        cfg = man["frames"][fn]["cells"]
        cells = res[fn]["cells"]
        out += ["## " + title, "", "| # | State | G100 | Differing pixels |", "|---|---|---|---|"]
        for i, name in enumerate(cfg["names"]):
            c = cells[str(i)]
            cls = "exact" if c["ok"] else ("approx" if c["approx"] else "**FAIL**")
            out.append("| %d | %s | %s | %.1f%% |" % (i, name, cls, 100 * c["frac"]))
        out.append("")
    if why:
        out += ["Approximate cells: " + why + ".", ""]
    open(os.path.join(ROOT, "docs", "combine-coverage.md"), "w").write("\n".join(out))


if __name__ == "__main__":
    main()
